package io.taig.blowout

import sbt.Keys.state
import sbt.io.IO
import sbt.plugins.JvmPlugin
import sbt.{AutoPlugin, Def, PluginTrigger, Plugins}

import java.io.FileNotFoundException

object BlowoutPlugin extends AutoPlugin {
  object autoImport extends BlowoutKeys {
    type BlowoutGenerator = io.taig.blowout.BlowoutGenerator
    val BlowoutGenerator = io.taig.blowout.BlowoutGenerator
  }

  import autoImport._

  override def requires: Plugins = JvmPlugin

  override def trigger: PluginTrigger = allRequirements

  override def projectSettings: Seq[Def.Setting[_]] = Def.settings(
    blowoutGenerators := Nil,
    blowoutHeader := {
      val hash =
        """# This file was automatically generated by sbt-blowout and should not be edited manually.
          |# Instead, run blowoutGenerate after making the desired changes to your build definition.""".stripMargin

      Map("conf" -> hash, "yml" -> hash)
    },
    blowoutGenerate := {
      blowoutGenerators.value.map { generator =>
        IO.write(generator.target, generator.content())
        generator.target
      }
    },
    blowoutCheck := {
      val log = state.value.log

      blowoutGenerators.value.foreach { generator =>
        try {
          val content = IO.read(generator.target)
          val expected = generator.content()

          if (content != expected) {
            log.error(s"Expected:\n$expected")
            log.error(s"Actual:\n$content")
            sys.error(
              s"${generator.target} does not contain contents that would have been generated by sbt-blowout; try running blowoutGenerate"
            )
          }
        } catch {
          case _: FileNotFoundException => sys.error(s"${generator.target} does not exist; try running blowoutGenerate")
        }
      }
    }
  )
}
